### ISSUE TITLE
Error codes + atualização da variável $?

### ISSUE THREAD

**Issue by mateuspinna** [speedshell/minishell#57]
Os comandos devem retornar erro compativel com o que se recebe no bash.

Os códigos de erro devem ser atualizados a cada comando e ficarem disponíveis quando quando expandirmos  a variável $?.

Esta variável será global e deve ser inicializada logo no inicio do programa para evitar erros. Por ser uma variavel builtin ela não deve ser armazenada em env.

**Comment by Leofariasrj25** [comment]
vou declarar a variável global no minishell.h e implementar a expansão desta variável dentro de expander.c
